### ISSUE TITLE
implement state update job

### ISSUE THREAD

**Issue by apoorvsadana** [karnotxyz/madara-orchestrator#13]
Implement state update job here - https://github.com/karnotxyz/madara-orchestrator/blob/2a9d77b7188afadefe3feba3347a909fc83299ed/crates/orchestrator/src/jobs/state_update_job/mod.rs#L12

1. Assume the proof has been verified on the base chain already
2. Make the state update generic across settlement layers (Etheruem or Starknet for now)
3. Implement the logic inside `settlement_clients` similar to how its done in #7 
4. If the PR #12 is already in progress, sync with it to avoid conflicts
5. For Ethereum, implement `update_state_blobs`. We need to figure out how to calculate `kzg_proof` here
6. For Starknet, implement `update_state_calldata`. We need to figure out how to calculate `onchain_data_hash` and `onchain_data_size` here

**Comment by akhercha** [comment]
Hey! Can I check this one? :)
