### ISSUE TITLE
implement Avail DA

### ISSUE THREAD

**Issue by 0x5ea000000** [karnotxyz/madara-orchestrator#31]
implement Avail as an option for data availability

> Ethereum 4844 DA support should be added with this PR - #7. Adding new DA layers should be very similar to this approach. The steps would be
> 
> 1. Create a new crate inside `da_clients`
> 2. Implement the `DaClient` trait from `da-client-interface`
>    
>    * `publish_state_diff`: push the data on chain and return the txn_hash
>    * `verify_inclusion`: taking the txn_hash as input, check if the txn has been finalized on chain

**Comment by 0x5ea000000** [comment]
@apoorvsadana Can I take this issue?

**Comment by ocdbytes** [comment]
Hey @0x5ea000000 

Someone else is also working on this issue. Closing this for now.

Thanks
